### ISSUE TITLE
UFO ALTREP sum explosion

### ISSUE THREAD

**Issue by kondziu** [PRL-PRG/UFOs#12]
```
library(ufoaltrep)
setwd("~/Workspace/ufo_workspace/UFOs/ufovectors/benchmark")
sum(altrep_ufo_integer_bin("32Mints.bin"))
```

```
Program received signal SIGSEGV, Segmentation fault.
0x0000555555743d3d in isum (sx=sx@entry=0x555557ccd9f0, value=value@entry=0x7fffffffc850, narm=narm@entry=FALSE, call=0x555557cae4c0) at summary.c:78
78	    ITERATE_BY_REGION(sx, x, i, nbatch, int, INTEGER, {
(gdb) backtrace 10
#0  0x0000555555743d3d in isum (sx=sx@entry=0x555557ccd9f0, value=value@entry=0x7fffffffc850, narm=narm@entry=FALSE, call=0x555557cae4c0) at summary.c:78
#1  0x0000555555744f18 in do_summary (call=0x555557cae4c0, op=<optimized out>, args=<optimized out>, env=<optimized out>) at summary.c:768
#2  0x0000555555689781 in Rf_eval (e=e@entry=0x555557cae4c0, rho=rho@entry=0x555555c19c90) at eval.c:727
#3  0x00005555556b844d in Rf_ReplIteration (rho=0x555555c19c90, savestack=0, browselevel=0, state=0x7fffffffcb00) at main.c:260
#4  0x00005555556b8811 in R_ReplConsole (rho=0x555555c19c90, savestack=0, browselevel=0) at main.c:310
#5  0x00005555556b88c2 in run_Rmainloop () at main.c:1086
#6  0x00005555556b8912 in Rf_mainloop () at main.c:1093
#7  0x00005555555bf838 in main (ac=ac@entry=1, av=av@entry=0x7fffffffdc48) at Rmain.c:29
#8  0x00007ffff587cb97 in __libc_start_main (main=0x5555555bf820 <main>, argc=1, argv=0x7fffffffdc48, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, 
    stack_end=0x7fffffffdc38) at ../csu/libc-start.c:310
#9  0x00005555555bf86a in _start ()
```

**Comment by kondziu** [comment]
Cannot reproduce?

**Comment by kondziu** [comment]
Ok, this was stupid.
